### ISSUE TITLE
Manager ignores it when AGFI create is failed

### ISSUE THREAD

**Issue by farzadfch** [firesim/firesim#327] opened 2019-07-27 00:23 UTC
In the build process, manager assumes that AGFI is created successfully even if `describe-fpga-images` says it's failed. This is discussed on the forum [here](https://groups.google.com/d/msg/firesim/CaquJ3Y9PnY/0kwzvqtiCwAJ).

**Comment by davidbiancolin** [comment] 2019-07-30 17:16
Based on the google groups chat, the root cause seems to be a duplicate of #293. In any case, the manager should still handle these failure cases better.

**Closed** 2020-06-01 06:27 UTC
